### ISSUE TITLE
mydumper segfaults when running as daemon

### ISSUE THREAD

**Issue by philfry** [maxbube/mydumper#116]
Using CentOS 7.4, selinux is enabled.

* using the precompiled `mydumper-0.9.3-41.el7.x86_64.rpm`:
```
$ mydumper -D -o /tmp/foo
$ *** Error in `mydumper': double free or corruption (out): 0x00007f73cc022890 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7c619)[0x7f73d3ecb619]
mydumper(exec_thread+0x3d)[0x41d4bd]
/lib64/libglib-2.0.so.0(+0x70f35)[0x7f73d48fcf35]
/lib64/libpthread.so.0(+0x7e25)[0x7f73d5b9ce25]
/lib64/libc.so.6(clone+0x6d)[0x7f73d3f4734d]
======= Memory map: ========
00400000-0073a000 r-xp 00000000 fd:01 1806                               /usr/bin/mydumper
0093a000-0093d000 r--p 0033a000 fd:01 1806                               /usr/bin/mydumper
0093d000-009b1000 rw-p 0033d000 fd:01 1806                               /usr/bin/mydumper
009b1000-009b6000 rw-p 00000000 00:00 0 
021ee000-0220f000 rw-p 00000000 00:00 0                                  [heap]
7f73bc000000-7f73bc166000 rw-p 00000000 00:00 0 
7f73bc166000-7f73c0000000 ---p 00000000 00:00 0 
7f73c0000000-7f73c015c000 rw-p 00000000 00:00 0 
7f73c015c000-7f73c4000000 ---p 00000000 00:00 0 
7f73c4000000-7f73c429b000 rw-p 00000000 00:00 0 
7f73c429b000-7f73c8000000 ---p 00000000 00:00 0 
7f73c8000000-7f73c8121000 rw-p 00000000 00:00 0 
7f73c8121000-7f73cc000000 ---p 00000000 00:00 0 
7f73cc000000-7f73cc144000 rw-p 00000000 00:00 0 
7f73cc144000-7f73d0000000 ---p 00000000 00:00 0 
7f73d0278000-7f73d0279000 ---p 00000000 00:00 0 
7f73d0279000-7f73d0a79000 rw-p 00000000 00:00 0 
7f73d0a79000-7f73d0a7a000 ---p 00000000 00:00 0 
7f73d0a7a000-7f73d127a000 rw-p 00000000 00:00 0 
7f73d127a000-7f73d127b000 ---p 00000000 00:00 0 
7f73d127b000-7f73d1a7b000 rw-p 00000000 00:00 0 
7f73d1a7b000-7f73d1a7c000 ---p 00000000 00:00 0 
7f73d1a7c000-7f73d227c000 rw-p 00000000 00:00 0 
7f73d227c000-7f73d2288000 r-xp 00000000 fd:01 24004                      /usr/lib64/libnss_files-2.17.so
7f73d2288000-7f73d2487000 ---p 0000c000 fd:01 24004                      /usr/lib64/libnss_files-2.17.so
7f73d2487000-7f73d2488000 r--p 0000b000 fd:01 24004                      /usr/lib64/libnss_files-2.17.so
7f73d2488000-7f73d2489000 rw-p 0000c000 fd:01 24004                      /usr/lib64/libnss_files-2.17.so
7f73d2489000-7f73d248f000 rw-p 00000000 00:00 0 
7f73d248f000-7f73d2490000 ---p 00000000 00:00 0 
7f73d2490000-7f73d2c90000 rw-p 00000000 00:00 0 
7f73d2c90000-7f73d2cb4000 r-xp 00000000 fd:01 30758                      /usr/lib64/libselinux.so.1
7f73d2cb4000-7f73d2eb3000 ---p 00024000 fd:01 30758                      /usr/lib64/libselinux.so.1
7f73d2eb3000-7f73d2eb4000 r--p 00023000 fd:01 30758                      /usr/lib64/libselinux.so.1
7f73d2eb4000-7f73d2eb5000 rw-p 00024000 fd:01 30758                      /usr/lib64/libselinux.so.1
7f73d2eb5000-7f73d2eb7000 rw-p 00000000 00:00 0 
7f73d2eb7000-7f73d2ecd000 r-xp 00000000 fd:01 27461                      /usr/lib64/libresolv-2.17.so
7f73d2ecd000-7f73d30cd000 ---p 00016000 fd:01 27461                      /usr/lib64/libresolv-2.17.so
7f73d30cd000-7f73d30ce000 r--p 00016000 fd:01 27461                      /usr/lib64/libresolv-2.17.so
7f73d30ce000-7f73d30cf000 rw-p 00017000 fd:01 27461                      /usr/lib64/libresolv-2.17.so
7f73d30cf000-7f73d30d1000 rw-p 00000000 00:00 0 
7f73d30d1000-7f73d30d4000 r-xp 00000000 fd:01 4258                       /usr/lib64/libkeyutils.so.1.5
7f73d30d4000-7f73d32d3000 ---p 00003000 fd:01 4258                       /usr/lib64/libkeyutils.so.1.5
7f73d32d3000-7f73d32d4000 r--p 00002000 fd:01 4258                       /usr/lib64/libkeyutils.so.1.5
7f73d32d4000-7f73d32d5000 rw-p 00003000 fd:01 4258                       /usr/lib64/libkeyutils.so.1.5
7f73d32d5000-7f73d32e2000 r-xp 00000000 fd:01 31655                      /usr/lib64/libkrb5support.so.0.1
7f73d32e2000-7f73d34e1000 ---p 0000d000 fd:01 31655                      /usr/lib64/libkrb5support.so.0.1
7f73d34e1000-7f73d34e2000 r--p 0000c000 fd:01 31655                      /usr/lib64/libkrb5support.so.0.1
7f73d34e2000-7f73d34e3000 rw-p 0000d000 fd:01 31655                      /usr/lib64/libkrb5support.so.0.1
7f73d34e3000-7f73d3514000 r-xp 00000000 fd:01 28302                      /usr/lib64/libk5crypto.so.3.1
7f73d3514000-7f73d3713000 ---p 00031000 fd:01 28302                      /usr/lib64/libk5crypto.so.3.1
7f73d3713000-7f73d3715000 r--p 00030000 fd:01 28302                      /usr/lib64/libk5crypto.so.3.1
7f73d3715000-7f73d3716000 rw-p 00032000 fd:01 28302                      /usr/lib64/libk5crypto.so.3.1
7f73d3716000-7f73d3719000 r-xp 00000000 fd:01 8045                       /usr/lib64/libcom_err.so.2.1
7f73d3719000-7f73d3918000 ---p 00003000 fd:01 8045                       /usr/lib64/libcom_err.so.2.1
7f73d3918000-7f73d3919000 r--p 00002000 fd:01 8045                       /usr/lib64/libcom_err.so.2.1
7f73d3919000-7f73d391a000 rw-p 00003000 fd:01 8045                       /usr/lib64/libcom_err.so.2.1
7f73d391a000-7f73d39f2000 r-xp 00000000 fd:01 28308                      /usr/lib64/libkrb5.so.3.3
7f73d39f2000-7f73d3bf1000 ---p 000d8000 fd:01 28308                      /usr/lib64/libkrb5.so.3.3
7f73d3bf1000-7f73d3bff000 r--p 000d7000 fd:01 28308                      /usr/lib64/libkrb5.so.3.3
7f73d3bff000-7f73d3c02000 rw-p 000e5000 fd:01 28308                      /usr/lib64/libkrb5.so.3.3
7f73d3c02000-7f73d3c4c000 r-xp 00000000 fd:01 4045                       /usr/lib64/libgssapi_krb5.so.2.2
7f73d3c4c000-7f73d3e4c000 ---p 0004a000 fd:01 4045                       /usr/lib64/libgssapi_krb5.so.2.2
7f73d3e4c000-7f73d3e4d000 r--p 0004a000 fd:01 4045                       /usr/lib64/libgssapi_krb5.so.2.2
7f73d3e4d000-7f73d3e4f000 rw-p 0004b000 fd:01 4045                       /usr/lib64/libgssapi_krb5.so.2.2
7f73d3e4f000-7f73d4007000 r-xp 00000000 fd:01 13088                      /usr/lib64/libc-2.17.so
7f73d4007000-7f73d4207000 ---p 001b8000 fd:01 13088                      /usr/lib64/libc-2.17.so
7f73d4207000-7f73d420b000 r--p 001b8000 fd:01 13088                      /usr/lib64/libc-2.17.so
7f73d420b000-7f73d420d000 rw-p 001bc000 fd:01 13088                      /usr/lib64/libc-2.17.so
7f73d420d000-7f73d4212000 rw-p 00000000 00:00 0 
7f73d4212000-7f73d4227000 r-xp 00000000 fd:01 23812                      /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f73d4227000-7f73d4426000 ---p 00015000 fd:01 23812                      /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f73d4426000-7f73d4427000 r--p 00014000 fd:01 23812                      /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f73d4427000-7f73d4428000 rw-p 00015000 fd:01 23812                      /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f73d4428000-7f73d4488000 r-xp 00000000 fd:01 30744                      /usr/lib64/libpcre.so.1.2.0
7f73d4488000-7f73d4688000 ---p 00060000 fd:01 30744                      /usr/lib64/libpcre.so.1.2.0
7f73d4688000-7f73d4689000 r--p 00060000 fd:01 30744                      /usr/lib64/libpcre.so.1.2.0
7f73d4689000-7f73d468a000 rw-p 00061000 fd:01 30744                      /usr/lib64/libpcre.so.1.2.0
7f73d468a000-7f73d468b000 r-xp 00000000 fd:01 39580                      /usr/lib64/libgthread-2.0.so.0.5000.3
7f73d468b000-7f73d488a000 ---p 00001000 fd:01 39580                      /usr/lib64/libgthread-2.0.so.0.5000.3
7f73d488a000-7f73d488b000 r--p 00000000 fd:01 39580                      /usr/lib64/libgthread-2.0.so.0.5000.3
7f73d488b000-7f73d488c000 rw-p 00001000 fd:01 39580                      /usr/lib64/libgthread-2.0.so.0.5000.3
7f73d488c000-7f73d499b000 r-xp 00000000 fd:01 39550                      /usr/lib64/libglib-2.0.so.0.5000.3
7f73d499b000-7f73d4b9b000 ---p 0010f000 fd:01 39550                      /usr/lib64/libglib-2.0.so.0.5000.3
7f73d4b9b000-7f73d4b9c000 r--p 0010f000 fd:01 39550                      /usr/lib64/libglib-2.0.so.0.5000.3
7f73d4b9c000-7f73d4b9d000 rw-p 00110000 fd:01 39550                      /usr/lib64/libglib-2.0.so.0.5000.3
7f73d4b9d000-7f73d4b9e000 rw-p 00000000 00:00 0 
7f73d4b9e000-7f73d4ba0000 r-xp 00000000 fd:01 21505                      /usr/lib64/libdl-2.17.so
7f73d4ba0000-7f73d4da0000 ---p 00002000 fd:01 21505                      /usr/lib64/libdl-2.17.so
7f73d4da0000-7f73d4da1000 r--p 00002000 fd:01 21505                      /usr/lib64/libdl-2.17.so
7f73d4da1000-7f73d4da2000 rw-p 00003000 fd:01 21505                      /usr/lib64/libdl-2.17.so
7f73d4da2000-7f73d4fd6000 r-xp 00000000 fd:01 31706                      /usr/lib64/libcrypto.so.1.0.2k
7f73d4fd6000-7f73d51d6000 ---p 00234000 fd:01 31706                      /usr/lib64/libcrypto.so.1.0.2k
7f73d51d6000-7f73d51f2000 r--p 00234000 fd:01 31706                      /usr/lib64/libcrypto.so.1.0.2k
7f73d51f2000-7f73d51ff000 rw-p 00250000 fd:01 31706                      /usr/lib64/libcrypto.so.1.0.2k
7f73d51ff000-7f73d5203000 rw-p 00000000 00:00 0 
7f73d5203000-7f73d526a000 r-xp 00000000 fd:01 40885                      /usr/lib64/libssl.so.1.0.2k
7f73d526a000-7f73d546a000 ---p 00067000 fd:01 40885                      /usr/lib64/libssl.so.1.0.2k
7f73d546a000-7f73d546e000 r--p 00067000 fd:01 40885                      /usr/lib64/libssl.so.1.0.2k
7f73d546e000-7f73d5475000 rw-p 0006b000 fd:01 40885                      /usr/lib64/libssl.so.1.0.2k
7f73d5475000-7f73d547c000 r-xp 00000000 fd:01 27720                      /usr/lib64/librt-2.17.so
7f73d547c000-7f73d567b000 ---p 00007000 fd:01 27720                      /usr/lib64/librt-2.17.so
7f73d567b000-7f73d567c000 r--p 00006000 fd:01 27720                      /usr/lib64/librt-2.17.so
7f73d567c000-7f73d567d000 rw-p 00007000 fd:01 27720                      /usr/lib64/librt-2.17.so
7f73d567d000-7f73d577e000 r-xp 00000000 fd:01 21522                      /usr/lib64/libm-2.17.so
7f73d577e000-7f73d597d000 ---p 00101000 fd:01 21522                      /usr/lib64/libm-2.17.so
7f73d597d000-7f73d597e000 r--p 00100000 fd:01 21522                      /usr/lib64/libm-2.17.so
7f73d597e000-7f73d597f000 rw-p 00101000 fd:01 21522                      /usr/lib64/libm-2.17.so
7f73d597f000-7f73d5994000 r-xp 00000000 fd:01 3523                       /usr/lib64/libz.so.1.2.7
7f73d5994000-7f73d5b93000 ---p 00015000 fd:01 3523                       /usr/lib64/libz.so.1.2.7
7f73d5b93000-7f73d5b94000 r--p 00014000 fd:01 3523                       /usr/lib64/libz.so.1.2.7
7f73d5b94000-7f73d5b95000 rw-p 00015000 fd:01 3523                       /usr/lib64/libz.so.1.2.7
7f73d5b95000-7f73d5bac000 r-xp 00000000 fd:01 22631                      /usr/lib64/libpthread-2.17.so
7f73d5bac000-7f73d5dab000 ---p 00017000 fd:01 22631                      /usr/lib64/libpthread-2.17.so
7f73d5dab000-7f73d5dac000 r--p 00016000 fd:01 22631                      /usr/lib64/libpthread-2.17.so
7f73d5dac000-7f73d5dad000 rw-p 00017000 fd:01 22631                      /usr/lib64/libpthread-2.17.so
7f73d5dad000-7f73d5db1000 rw-p 00000000 00:00 0 
7f73d5db1000-7f73d5e9a000 r-xp 00000000 fd:01 27746                      /usr/lib64/libstdc++.so.6.0.19
7f73d5e9a000-7f73d609a000 ---p 000e9000 fd:01 27746                      /usr/lib64/libstdc++.so.6.0.19
7f73d609a000-7f73d60a2000 r--p 000e9000 fd:01 27746                      /usr/lib64/libstdc++.so.6.0.19
7f73d60a2000-7f73d60a4000 rw-p 000f1000 fd:01 27746                      /usr/lib64/libstdc++.so.6.0.19
7f73d60a4000-7f73d60b9000 rw-p 00000000 00:00 0 
7f73d60b9000-7f73d60da000 r-xp 00000000 fd:01 3513                       /usr/lib64/ld-2.17.so
7f73d62c0000-7f73d62cc000 rw-p 00000000 00:00 0 
7f73d62d8000-7f73d62d9000 rw-p 00000000 00:00 0 
7f73d62d9000-7f73d62da000 rw-p 00000000 00:00 0 
7f73d62da000-7f73d62db000 r--p 00021000 fd:01 3513                       /usr/lib64/ld-2.17.so
7f73d62db000-7f73d62dc000 rw-p 00022000 fd:01 3513                       /usr/lib64/ld-2.17.so
7f73d62dc000-7f73d62dd000 rw-p 00000000 00:00 0 
7fff47dc2000-7fff47de3000 rw-p 00000000 00:00 0                          [stack]
7fff47dfa000-7fff47dfc000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
```
* compiled from 057d3c3:
```
$ gdb mydumper
(gdb) set follow-fork-mode child             
(gdb) run -D -o /var/backup/foo
Starting program: /usr/bin/mydumper -D -o /tmp/fo
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New process 1540]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7ffff46b9700 (LWP 1541)]
[New Thread 0x7ffff3eb8700 (LWP 1542)]
[Thread 0x7ffff3eb8700 (LWP 1542) exited]
[tcsetpgrp failed in terminal_inferior: No such process]
[New Thread 0x7ffff3eb8700 (LWP 1544)]
[New Thread 0x7ffff34a4700 (LWP 1546)]
[New Thread 0x7ffff2ca3700 (LWP 1548)]
[New Thread 0x7ffff24a2700 (LWP 1550)]
[Thread 0x7ffff34a4700 (LWP 1546) exited]
[Thread 0x7ffff3eb8700 (LWP 1544) exited]
[Thread 0x7ffff24a2700 (LWP 1550) exited]
[Thread 0x7ffff2ca3700 (LWP 1548) exited]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff46b9700 (LWP 1541)]
0x0000003f00000000 in ?? ()
(gdb) bt                                     
#0  0x0000003f00000000 in ?? ()
#2  0x00007ffff790cf57 in net_real_write (net=net@entry=0x7fffec002d80, packet=0x7fffec01c6a0 "\001", len=5) at /usr/src/debug/mariadb-5.5.56/sql/net_serv.cc:588
#2  0x00007ffff790d243 in net_flush (net=net@entry=0x7fffec002d80) at /usr/src/debug/mariadb-5.5.56/sql/net_serv.cc:348
#3  0x00007ffff790d9ab in net_write_command (net=net@entry=0x7fffec002d80, command=command@entry=1 '\001', header=header@entry=0x0, head_len=head_len@entry=0, 
    packet=packet@entry=0x0, len=len@entry=0) at /usr/src/debug/mariadb-5.5.56/sql/net_serv.cc:487
#4  0x00007ffff7905232 in cli_advanced_command (mysql=0x7fffec002d80, command=<optimized out>, header=0x0, header_length=0, arg=0x0, arg_length=0, skip_check=1 '\001', stmt=0x0)
	    at /usr/src/debug/mariadb-5.5.56/sql-common/client.c:861
#5  0x00007ffff7902a64 in mysql_close_slow_part (mysql=mysql@entry=0x7fffec002d80) at /usr/src/debug/mariadb-5.5.56/sql-common/client.c:3901
#6  0x00007ffff7902a9c in mysql_close (mysql=mysql@entry=0x7fffec002d80) at /usr/src/debug/mariadb-5.5.56/sql-common/client.c:3913
#7  0x000000000040aa4d in exec_thread (data=<optimized out>) at /usr/src/debug/mydumper-0.9.4/mydumper.c:1011
#8  0x00007ffff662ef35 in g_thread_proxy (data=0x61b000) at gthread.c:784
#9  0x00007ffff76c6e25 in start_thread (arg=0x7ffff46b9700) at pthread_create.c:308
#10 0x00007ffff5e8f34d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113
```

**Comment by philfry** [comment]
seems to be fixed by #99 and by compiling against mariadb 10.2.
